[package]
name = "stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="stats"

[dependencies]
color-eyre = { version = "0.6.2", default-features = false }
itertools = "0.10.5"

